  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      app:
        image: yourusername/yourapp:latest
        ports:
          - 8080:8080
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          python3 -m pip install -r requirements.txt
          python3 api-test-example.py
